main param selection form can now also submit jobs directly
multiply-org/multiply-ui pull request #14
Opened 2019-05-27 18:35 UTC by forman

If you review this PR, make sure you execute the notebook `notebooks/mui-demo.ipynb` in parallel which explains the concepts introduced in the many code changes.

Note there are several open issues in this PR which may individually turned into separate issues and then PRs:

![image](https://user-images.githubusercontent.com/206773/58434918-5a61a100-80be-11e9-8e08-d487e9a7ce8c.png)

2019-05-29 11:29 UTC, thomasstorm commented on multiply_ui/ui/job/model.py
> +    PropertyDef("status", TypeDef(str, choices=['new', 'running', 'succeeded', 'cancelling', 'cancelled'])),
Maybe we'll need the status "failed" here?

2019-05-29 11:50 UTC, thomasstorm commented on notebooks/mui-demo.ipynb
>      "req"
Error message would be nice when req is None.

2019-05-29 11:50 UTC, thomasstorm commented on notebooks/mui-demo.ipynb
> +       "<div><p>Name: <br/>Time range: (datetime.datetime(2010, 1, 1, 0, 0), datetime.datetime(2019, 1, 1, 0, 0))<br/>Region box: (0.0, 0.0, 360.0, 180.0)Input types: S2_L1C</p><div><h4>Inputs</h4><t
Add line break after "Region Box: (...)"

2019-05-29 11:52 UTC, thomasstorm commented
If I run the notebook, I'll get errors after line
req.submit('my_job'), probably because of
'NameError: name 'my_job' is not defined'

2019-05-29 11:56 UTC, thomasstorm requested changes
See comments

2019-05-30 11:40 UTC, TonioF approved these changes
Just minor remarks.

2019-05-30 11:40 UTC, TonioF commented on multiply_ui/ui/__init__.py
> -from .data import data_ui
With these changes, Notebooks "multiply-ui-1.ipynb" and "multiply-ui-2.ipynb" have become obsolete. Please remove them, at the very least from "readme.txt"

2019-05-30 11:40 UTC, TonioF commented on multiply_ui/ui/req/form.py
> +    if mock:
I think a single "if mock" is enough.

2019-06-05 14:06 UTC, TonioF commented
I have considered the comments from @thomasstorm and myelf. I have further moved the submit mocking to the api module, so it can be used from both from and model. @forman , please have a look at https://github.com/multiply-org/multiply-ui/pull/14/commits/db8526f42da3d3b4a3050c89b4e121373b1f452c .

2019-06-05 15:41 UTC, TonioF commented
Or rather, look at https://github.com/multiply-org/multiply-ui/pull/14/commits/006855b7cbf2664851d138ecb676cb3add608e66

2019-06-05 15:49 UTC, thomasstorm approved these changes

2019-06-21 07:46 UTC, merged